apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    run: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: sontn1309/udagram-reverseproxy:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always